# Generated by Django 6.0.2 on 2026-02-09 07:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pipeline', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeeklyReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('week_start', models.DateField()),
                ('week_end', models.DateField()),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('generated', 'Generated'), ('reviewed', 'Reviewed'), ('published', 'Published')], default='draft', max_length=20)),
                ('executive_summary', models.TextField(blank=True)),
                ('signals_section', models.JSONField(blank=True, default=list)),
                ('opportunities', models.JSONField(blank=True, default=list)),
                ('threats', models.JSONField(blank=True, default=list)),
                ('tools_to_test', models.JSONField(blank=True, default=list)),
                ('project_ideas', models.JSONField(blank=True, default=list)),
                ('recommended_actions', models.JSONField(blank=True, default=list)),
                ('kpis', models.JSONField(blank=True, default=dict)),
                ('full_markdown', models.TextField(blank=True)),
                ('signal_count', models.PositiveIntegerField(default=0)),
                ('source_count', models.PositiveIntegerField(default=0)),
                ('processing_run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='weekly_reports', to='pipeline.processingrun')),
            ],
            options={
                'ordering': ['-week_start'],
                'unique_together': {('week_start', 'week_end')},
            },
        ),
    ]
