"""
PDF generation for weekly reports with professional styling.
Supports English (en) and French (fr) via a language parameter.
"""
import io
from datetime import datetime
from typing import Optional

from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import cm
from reportlab.lib.colors import HexColor, black, white
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle
from reportlab.lib.enums import TA_CENTER, TA_LEFT, TA_RIGHT

_STRINGS = {
    "en": {
        "title": "Weekly Market Intelligence Report",
        "week_range": "Week of {start} to {end}",
        "generated_date": "Generated on {date}",
        "signals_analyzed": "Signals analyzed: {count}",
        "sources_label": "Sources: {count}",
        "executive_summary": "Executive Summary",
        "no_summary": "No summary available.",
        "key_signals": "Key Signals Detected This Week",
        "no_signals": "No key signals detected this week.",
        "opportunities": "Concrete Opportunities to Exploit",
        "no_opportunities": "No opportunities identified this week.",
        "threats": "Threats and Risks to Anticipate",
        "no_threats": "No threats or risks identified this week.",
        "tools": "Tools / Technologies to Test",
        "no_tools": "No tools or technologies recommended this week.",
        "projects": "Project or Offer Ideas",
        "no_projects": "No project or offer ideas identified this week.",
        "kpis": "KPIs and Statistics",
        "kpi_total_signals": "Total signals",
        "kpi_sources": "Number of sources",
        "kpi_signals_per_source": "Signals per source",
        "footer": (
            '<font name="Helvetica" size="8" color="#6b7280">'
            "Report automatically generated by News Engine - {date}<br/>"
            "For any questions, contact the market intelligence team."
            "</font>"
        ),
    },
    "fr": {
        "title": "Rapport Hebdomadaire d'Intelligence March\u00e9",
        "week_range": "Semaine du {start} au {end}",
        "generated_date": "G\u00e9n\u00e9r\u00e9 le {date}",
        "signals_analyzed": "Signaux analys\u00e9s\u00a0: {count}",
        "sources_label": "Sources\u00a0: {count}",
        "executive_summary": "R\u00e9sum\u00e9 Ex\u00e9cutif",
        "no_summary": "Aucun r\u00e9sum\u00e9 disponible.",
        "key_signals": "Signaux Cl\u00e9s D\u00e9tect\u00e9s Cette Semaine",
        "no_signals": "Aucun signal cl\u00e9 d\u00e9tect\u00e9 cette semaine.",
        "opportunities": "Opportunit\u00e9s Concr\u00e8tes \u00e0 Exploiter",
        "no_opportunities": "Aucune opportunit\u00e9 identifi\u00e9e cette semaine.",
        "threats": "Menaces et Risques \u00e0 Anticiper",
        "no_threats": "Aucune menace ou risque identifi\u00e9 cette semaine.",
        "tools": "Outils / Technologies \u00e0 Tester",
        "no_tools": "Aucun outil ou technologie recommand\u00e9 cette semaine.",
        "projects": "Id\u00e9es de Projets ou d'Offres",
        "no_projects": "Aucune id\u00e9e de projet ou d'offre identifi\u00e9e cette semaine.",
        "kpis": "KPIs et Statistiques",
        "kpi_total_signals": "Total des signaux",
        "kpi_sources": "Nombre de sources",
        "kpi_signals_per_source": "Signaux par source",
        "footer": (
            '<font name="Helvetica" size="8" color="#6b7280">'
            "Rapport g\u00e9n\u00e9r\u00e9 automatiquement par News Engine - {date}<br/>"
            "Pour toute question, contactez l'\u00e9quipe d'intelligence march\u00e9."
            "</font>"
        ),
    },
}


class ReportPDFGenerator:
    """Generate professional PDF reports with modern styling in EN or FR."""

    def __init__(self, lang: str = "en"):
        self.lang = lang if lang in _STRINGS else "en"
        self.t = _STRINGS[self.lang]
        self.styles = getSampleStyleSheet()
        self._setup_custom_styles()
        self.page_width, self.page_height = A4
        self.margin = 2 * cm

    def _setup_custom_styles(self):
        """Setup custom styles for the report."""
        self.styles.add(ParagraphStyle(
            name='CustomTitle',
            parent=self.styles['Heading1'],
            fontSize=24,
            spaceAfter=30,
            textColor=HexColor('#1a1a1a'),
            alignment=TA_CENTER,
            borderWidth=0,
            borderColor=white,
        ))

        self.styles.add(ParagraphStyle(
            name='SectionHeader',
            parent=self.styles['Heading2'],
            fontSize=16,
            spaceBefore=20,
            spaceAfter=10,
            textColor=HexColor('#2563eb'),
            borderWidth=0,
            borderColor=white,
        ))

        self.styles.add(ParagraphStyle(
            name='Subsection',
            parent=self.styles['Heading3'],
            fontSize=12,
            spaceBefore=15,
            spaceAfter=8,
            textColor=HexColor('#4b5563'),
            borderWidth=0,
            borderColor=white,
        ))

        self.styles.add(ParagraphStyle(
            name='ReportBodyText',
            parent=self.styles['Normal'],
            fontSize=10,
            spaceAfter=6,
            textColor=HexColor('#374151'),
            leading=14,
        ))

        self.styles.add(ParagraphStyle(
            name='Summary',
            parent=self.styles['Normal'],
            fontSize=11,
            spaceAfter=12,
            textColor=HexColor('#1f2937'),
            backColor=HexColor('#f3f4f6'),
            borderColor=HexColor('#e5e7eb'),
            borderWidth=1,
            borderPadding=8,
            borderRadius=4,
        ))

        self.styles.add(ParagraphStyle(
            name='KPI',
            parent=self.styles['Normal'],
            fontSize=10,
            spaceAfter=4,
            textColor=HexColor('#059669'),
            alignment=TA_CENTER,
        ))

    def generate_pdf(self, report_data, output_buffer: Optional[io.BytesIO] = None) -> io.BytesIO:
        """Generate PDF report from report data."""
        if output_buffer is None:
            output_buffer = io.BytesIO()

        doc = SimpleDocTemplate(
            output_buffer,
            pagesize=A4,
            rightMargin=self.margin,
            leftMargin=self.margin,
            topMargin=self.margin,
            bottomMargin=self.margin,
        )

        story = []
        self._build_header(story, report_data)
        self._build_executive_summary(story, report_data)
        self._build_key_signals(story, report_data)
        self._build_opportunities(story, report_data)
        self._build_threats(story, report_data)
        self._build_tools_to_test(story, report_data)
        self._build_project_ideas(story, report_data)
        self._build_kpis(story, report_data)
        self._build_footer(story, report_data)

        doc.build(story)
        output_buffer.seek(0)
        return output_buffer

    def _build_header(self, story, report_data):
        """Build report header with title and metadata."""
        title = Paragraph(self.t["title"], self.styles['CustomTitle'])
        story.append(title)
        story.append(Spacer(1, 20))

        week_range = self.t["week_range"].format(
            start=report_data['week_start'], end=report_data['week_end'],
        )
        now_str = datetime.now().strftime('%d/%m/%Y %H:%M')
        generated_date = self.t["generated_date"].format(date=now_str)

        metadata_data = [
            [week_range, generated_date],
            [
                self.t["signals_analyzed"].format(count=report_data['signal_count']),
                self.t["sources_label"].format(count=report_data['source_count']),
            ],
        ]

        metadata_table = Table(metadata_data, colWidths=[8*cm, 8*cm])
        metadata_table.setStyle(TableStyle([
            ('ALIGN', (0, 0), (-1, -1), 'CENTER'),
            ('FONTNAME', (0, 0), (-1, -1), 'Helvetica'),
            ('FONTSIZE', (0, 0), (-1, -1), 10),
            ('TEXTCOLOR', (0, 0), (-1, -1), HexColor('#6b7280')),
            ('BOTTOMPADDING', (0, 0), (-1, -1), 12),
        ]))

        story.append(metadata_table)
        story.append(Spacer(1, 30))

    def _build_executive_summary(self, story, report_data):
        """Build executive summary section."""
        story.append(Paragraph(self.t["executive_summary"], self.styles['SectionHeader']))

        summary = report_data.get('executive_summary', self.t["no_summary"])
        if isinstance(summary, list):
            summary = ' '.join(summary) if summary else self.t["no_summary"]

        story.append(Paragraph(summary, self.styles['Summary']))
        story.append(Spacer(1, 20))

    def _build_key_signals(self, story, report_data):
        """Build key signals section."""
        story.append(Paragraph(self.t["key_signals"], self.styles['SectionHeader']))

        signals = report_data.get('signals_section', [])
        if not signals:
            story.append(Paragraph(self.t["no_signals"], self.styles['ReportBodyText']))
        else:
            for signal in signals[:10]:
                story.append(Paragraph(f"\u2022 {signal}", self.styles['ReportBodyText']))

        story.append(Spacer(1, 20))

    def _build_opportunities(self, story, report_data):
        """Build opportunities section."""
        story.append(Paragraph(self.t["opportunities"], self.styles['SectionHeader']))

        opportunities = report_data.get('opportunities', [])
        if not opportunities:
            story.append(Paragraph(self.t["no_opportunities"], self.styles['ReportBodyText']))
        else:
            for opportunity in opportunities[:8]:
                story.append(Paragraph(f"\u2022 {opportunity}", self.styles['ReportBodyText']))

        story.append(Spacer(1, 20))

    def _build_threats(self, story, report_data):
        """Build threats and risks section."""
        story.append(Paragraph(self.t["threats"], self.styles['SectionHeader']))

        threats = report_data.get('threats', [])
        if not threats:
            story.append(Paragraph(self.t["no_threats"], self.styles['ReportBodyText']))
        else:
            for threat in threats[:8]:
                story.append(Paragraph(f"\u2022 {threat}", self.styles['ReportBodyText']))

        story.append(Spacer(1, 20))

    def _build_tools_to_test(self, story, report_data):
        """Build tools and technologies section."""
        story.append(Paragraph(self.t["tools"], self.styles['SectionHeader']))

        tools = report_data.get('tools_to_test', [])
        if not tools:
            story.append(Paragraph(self.t["no_tools"], self.styles['ReportBodyText']))
        else:
            for tool in tools[:10]:
                story.append(Paragraph(f"\u2022 {tool}", self.styles['ReportBodyText']))

        story.append(Spacer(1, 20))

    def _build_project_ideas(self, story, report_data):
        """Build project or offer ideas section."""
        story.append(Paragraph(self.t["projects"], self.styles['SectionHeader']))

        projects = report_data.get('project_ideas', [])
        if not projects:
            story.append(Paragraph(self.t["no_projects"], self.styles['ReportBodyText']))
        else:
            for project in projects[:8]:
                story.append(Paragraph(f"\u2022 {project}", self.styles['ReportBodyText']))

        story.append(Spacer(1, 20))

    def _build_kpis(self, story, report_data):
        """Build KPIs and statistics section."""
        story.append(Paragraph(self.t["kpis"], self.styles['SectionHeader']))

        kpis = report_data.get('kpis', {})
        if not kpis:
            kpis = {
                self.t["kpi_total_signals"]: report_data.get('signal_count', 0),
                self.t["kpi_sources"]: report_data.get('source_count', 0),
                self.t["kpi_signals_per_source"]: (
                    report_data.get('signal_count', 0)
                    / max(1, report_data.get('source_count', 1))
                ),
            }

        kpi_data = []
        for key, value in kpis.items():
            formatted_value = f"{value:.1f}" if isinstance(value, float) else str(value)
            kpi_data.append([key, formatted_value])

        if kpi_data:
            kpi_table = Table(kpi_data, colWidths=[6*cm, 4*cm])
            kpi_table.setStyle(TableStyle([
                ('ALIGN', (0, 0), (-1, -1), 'LEFT'),
                ('ALIGN', (1, 0), (1, -1), 'RIGHT'),
                ('FONTNAME', (0, 0), (-1, -1), 'Helvetica'),
                ('FONTSIZE', (0, 0), (-1, -1), 10),
                ('TEXTCOLOR', (0, 0), (-1, -1), HexColor('#374151')),
                ('GRID', (0, 0), (-1, -1), 1, HexColor('#e5e7eb')),
                ('BACKGROUND', (0, 0), (0, -1), HexColor('#f9fafb')),
                ('BACKGROUND', (1, 0), (1, -1), HexColor('#ffffff')),
                ('PADDING', (0, 0), (-1, -1), 8),
            ]))
            story.append(kpi_table)

        story.append(Spacer(1, 30))

    def _build_footer(self, story, report_data):
        """Build report footer."""
        story.append(Spacer(1, 20))
        now_str = datetime.now().strftime('%d/%m/%Y %H:%M')
        footer_text = self.t["footer"].format(date=now_str)
        story.append(Paragraph(footer_text, self.styles['ReportBodyText']))
