# Generated by Django 6.0.2 on 2026-02-09 07:47

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('articles', '0001_initial'),
        ('pipeline', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Signal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.CharField(choices=[('emerging_needs', 'Emerging customer needs'), ('pain_points', 'Recurring business pain points'), ('saas_opportunities', 'SaaS or packaged services opportunities'), ('competitive_moves', 'Competitive movements'), ('regulatory_changes', 'Regulatory or legal changes'), ('pricing_pressure', 'Pricing pressure and commoditization'), ('acquisition_channels', 'New acquisition channels'), ('new_tech', 'New frameworks, CMS, AI tools'), ('automation_devops', 'Automation, CI/CD, performance, security'), ('ai_applied', 'AI applied to dev, SEO, design, PM'), ('ai_agents', 'AI agents, copilots, RPA'), ('legal_risks', 'Legal and technical risks')], max_length=32)),
                ('title', models.CharField(max_length=512)),
                ('description', models.TextField()),
                ('relevance_score', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('confidence', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('entities', models.JSONField(blank=True, default=list)),
                ('raw_llm_output', models.JSONField(default=dict)),
                ('is_validated', models.BooleanField(default=False)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signals', to='articles.article')),
                ('chunk', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='signals', to='articles.contentchunk')),
                ('processing_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signals', to='pipeline.processingrun')),
            ],
            options={
                'ordering': ['-relevance_score', '-created_at'],
            },
        ),
    ]
