# Generated by Django 4.2.28 on 2026-02-10 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("intelligence", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PromptTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=128, unique=True)),
                ("purpose", models.CharField(blank=True, max_length=128)),
                (
                    "body",
                    models.TextField(help_text="Full prompt text sent to the LLM."),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
    ]
