# Generated by Django 4.2.28 on 2026-02-10 09:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("pipeline", "0001_initial"),
        ("intelligence", "0002_prompttemplate"),
    ]

    operations = [
        migrations.AlterField(
            model_name="signal",
            name="processing_run",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="signals",
                to="pipeline.processingrun",
            ),
        ),
    ]
