# Generated by Django 6.0.2 on 2026-02-10 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intelligence', '0003_alter_signal_processing_run'),
    ]

    operations = [
        migrations.CreateModel(
            name='SimpleNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=512)),
                ('content', models.TextField()),
                ('category', models.CharField(blank=True, choices=[('emerging_needs', 'Emerging customer needs'), ('pain_points', 'Recurring business pain points'), ('saas_opportunities', 'SaaS or packaged services opportunities'), ('competitive_moves', 'Competitive movements'), ('regulatory_changes', 'Regulatory or legal changes'), ('pricing_pressure', 'Pricing pressure and commoditization'), ('acquisition_channels', 'New acquisition channels'), ('new_tech', 'New frameworks, CMS, AI tools'), ('automation_devops', 'Automation, CI/CD, performance, security'), ('ai_applied', 'AI applied to dev, SEO, design, PM'), ('ai_agents', 'AI agents, copilots, RPA'), ('legal_risks', 'Legal and technical risks')], max_length=32)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
