# Generated by Django 6.0.2 on 2026-02-09 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('url', models.URLField(unique=True)),
                ('source_type', models.CharField(choices=[('website', 'Website'), ('rss', 'RSS'), ('api', 'API')], default='website', max_length=20)),
                ('scrape_strategy', models.CharField(choices=[('playwright', 'Playwright'), ('trafilatura', 'Trafilatura'), ('rss', 'RSS')], default='trafilatura', max_length=20)),
                ('frequency_minutes', models.PositiveIntegerField(default=360, help_text='Scrape interval in minutes (default 6h = 360)')),
                ('is_active', models.BooleanField(default=True)),
                ('css_selector', models.TextField(blank=True, help_text='Optional CSS selector for article list')),
                ('last_scraped_at', models.DateTimeField(blank=True, null=True)),
                ('config', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
