# Generated by Django 4.2.28 on 2026-02-19 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pipeline', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='processingrun',
            name='progress_current',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='processingrun',
            name='progress_phase',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
        migrations.AddField(
            model_name='processingrun',
            name='progress_total',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
